import { palette } from './pallete';

export const theme = {
  text: {
    primary: palette.black[100],
    secondary: palette.black[80],
    muted: palette.black[60],
    accent: palette.blue[500],
  },
  background: {
    primary: palette.white[100],
    secondary: palette.lightGray[100],
    muted: palette.gray[50],
    accent: palette.blue[500],
  },
  fileUpload: {
    text: palette.blue[500],
    background: 'transparent',
    backgroundHover: palette.blue[10],
    backgroundActive: palette.blue[20],
    backgroundOverlay: palette.gray[60],
    deleted: {
      text: palette.red[100],
      background: palette.black[60],
    },
  },
  action: {
    primary: {
      text: palette.black[80],
      background: 'transparent',
      backgroundHover: palette.gray[60],
      backgroundActive: palette.gray[80],
      border: palette.gray[40],
    },
    accent: {
      text: palette.white[100],
      background: palette.blue[500],
      backgroundHover: palette.blue[700],
      backgroundActive: palette.blue[900],
      border: palette.blue[500],
    },
    secondary: {
      text: palette.blue[500],
      background: palette.white[100],
      backgroundHover: palette.gray[60],
      backgroundActive: palette.gray[80],
      border: palette.white[100],
    },
    muted: {
      text: palette.black[40],
      background: 'transparent',
      backgroundHover: palette.gray[60],
      backgroundActive: palette.gray[80],
      border: palette.gray[40],
    },
    success: {
      text: palette.green[100],
      background: palette.green[10],
      backgroundHover: palette.green[30],
      backgroundActive: palette.green[50],
      border: palette.green[100],
    },
    danger: {
      text: palette.red[100],
      background: palette.red[10],
      backgroundHover: palette.red[30],
      backgroundActive: palette.red[50],
      border: palette.red[100],
    },
    info: {
      text: palette.blue[80],
      background: palette.blue[10],
      backgroundHover: palette.blue[30],
      backgroundActive: palette.blue[50],
      border: palette.blue[80],
    },
    neutral: {
      text: palette.black[60],
      background: palette.gray[40],
      backgroundHover: palette.gray[60],
      backgroundActive: palette.gray[80],
      border: palette.black[60],
    },
    disabled: {
      text: palette.black[60],
      background: palette.gray[100],
      border: palette.gray[100],
    },
  },
  border: {
    primary: palette.gray[80],
    secondary: palette.gray[60],
    muted: palette.gray[40],
    accent: palette.blue[500],
    danger: palette.red[100],
    success: palette.green[100],
  },
  status: {
    success: palette.green[100],
    danger: palette.red[100],
    info: palette.blue[80],
    default: palette.black[40],
  },
  scrollbar: {
    track: 'transparent',
    thumb: palette.black[30],
    thumbHover: palette.black[40],
  },
  modal: {
    background: palette.white[100],
    backgroundOverlay: palette.black[10],
  },
  container: {
    authForm: '428px',
    page: '1440px',
  },
  lineHeight: {
    xs: 1,
    sm: 1.2,
    md: 1.4,
    lg: 1.5,
    xl: 1.6,
  },
  pagination: {
    width: '40px',
    height: '40px',
    disabled: {
      text: palette.black[10],
    },
  },
  fontFamily: {
    inter: 'Inter, sans-serif',
  },
  size: {
    pagination: {
      width: '44px',
      height: '44px',
    },
    scrollbar: {
      width: '2px',
      height: '2px',
    },
    icon: {
      xs2: '14px',
      xs: '16px',
      sm: '18px',
      md: '20px',
      lg: '22px',
      xl: '24px',
      xl2: '28px',
      xl3: '32px',
      xl4: '36px',
      xl5: '40px',
      xl6: '44px',
    },
  },
  fontSize: {
    xs5: '8px',
    xs4: '9px',
    xs3: '10px',
    xs2: '11px',
    xs: '12px',
    sm: '13px',
    md: '14px',
    lg: '15px',
    xl: '16px',
    xl2: '17px',
    xl3: '18px',
    xl4: '19px',
    xl5: '20px',
    xl6: '22px',
    xl7: '24px',
    xl8: '28px',
  },
  fontWeight: {
    regular: 400,
    medium: 500,
    semibold: 600,
  },
  zIndex: {
    dropdown: 1000,
    modalOverlay: 1100,
    modal: 1200,
  },
  borderWidth: {
    xs: '1px',
    sm: '2px',
    md: '4px',
    lg: '8px',
  },
  borderRadius: {
    xs4: '2px',
    xs3: '4px',
    xs2: '6px',
    xs: '8px',
    sm: '10px',
    md: '12px',
    lg: '14px',
    xl: '16px',
    xl2: '18px',
    xl3: '20px',
  },
  spacing: {
    xs7: '2px',
    xs6: '4px',
    xs5: '6px',
    xs4: '8px',
    xs3: '10px',
    xs2: '12px',
    xs: '14px',
    sm: '16px',
    md: '18px',
    lg: '20px',
    xl: '22px',
    xl2: '24px',
    xl3: '26px',
    xl4: '28px',
    xl5: '30px',
    xl6: '32px',
    xl7: '36px',
    xl8: '40px',
  },
  transitionDuration: {
    xs: '100ms',
    sm: '200ms',
    md: '300ms',
    lg: '400ms',
    xl: '600ms',
  },
  shadow: {
    sm: `0 2px 4px ${palette.black[5]}`,
    md: `0 4px 8px ${palette.black[5]}`,
    lg: `0 8px 16px ${palette.black[5]}`,
    default: `0 0 10px 0 ${palette.black[5]}`,
  },
};

export type Theme = typeof theme;
